name: "Lint PR"

on:
  workflow_call:
    secrets:
      GIT_HUB_PAT:
        description: "GitHub Personal Access Token for authentication"
        required: true

jobs:
  main:
    name: Validate PR title
    runs-on: ubuntu-22.04
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        with:
          wip: true
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_HUB_PAT }}
