name: "Lint PR"

on: 
  workflow_call:
    secrets:
      GITHUB_TOKEN:
        description: "GitHub Token for authentication"
        required: true

permissions:
  pull-requests: write

jobs:
  main:
    name: Validate PR title
    runs-on: ubuntu-latest
    steps:
      - name: Use semantic pull request action
        uses: amannn/action-semantic-pull-request@v5
        with:
          wip: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
